import React from 'react';
import { motion } from 'framer-motion';
import { ShieldAlert, Brain, Clock, Activity, Calendar, Award, Thermometer, CheckCircle2 } from 'lucide-react';

const AnalysisResult = ({ result, onProceed }) => {
    if (!result) return null;

    const confidencePercentage = result.confidence ? Math.round(result.confidence * 100) : 85;

    return (
        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} className="glass-card" style={{ maxWidth: '850px', margin: '2rem auto', padding: '3.5rem', borderRadius: '32px', border: '1px solid var(--border-subtle)', boxShadow: '0 40px 80px -20px rgba(0,0,0,0.15)', position: 'relative', overflow: 'hidden' }}>
            
            {/* Background Glow */}
            <div style={{ position: 'absolute', top: '-10%', right: '-10%', width: '300px', height: '300px', background: 'var(--primary-plus)', borderRadius: '50%', filter: 'blur(100px)', opacity: 0.2, zIndex: 0 }} />

            {/* Disclaimer */}
            <div style={{ display: 'flex', alignItems: 'start', gap: '1.25rem', background: 'rgba(255, 193, 7, 0.05)', borderRadius: '20px', padding: '1.5rem', border: '1px solid rgba(255, 193, 7, 0.2)', marginBottom: '3rem', position: 'relative', zIndex: 1 }}>
                <ShieldAlert size={28} style={{ color: '#f59e0b', flexShrink: 0 }} />
                <p style={{ margin: 0, color: '#92400e', fontSize: '0.9rem', lineHeight: '1.6', fontWeight: 600 }}>
                    <strong style={{ display: 'block', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '0.25rem' }}>Medical Intelligence Disclaimer</strong>
                    This analysis is generated by a high-fidelity clinical AI node. It is intended for navigational triage and informative purposes only. Consult a human specialist for definitive diagnosis.
                </p>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '2.5rem', paddingBottom: '2.5rem', borderBottom: '1px solid var(--border-subtle)', position: 'relative', zIndex: 1 }}>
                <div>
                    <h3 style={{ margin: '0 0 0.75rem', color: 'var(--text-soft)', textTransform: 'uppercase', fontSize: '0.8rem', fontWeight: 900, letterSpacing: '2px' }}>
                        Targeted Department
                    </h3>
                    <div style={{ fontSize: '2.5rem', fontWeight: 900, color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '1rem', letterSpacing: '-1.5px', fontFamily: 'Outfit, sans-serif' }}>
                        <div style={{ width: '56px', height: '56px', borderRadius: '18px', background: 'var(--primary-plus)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--primary)' }}>
                            <Activity size={32} />
                        </div>
                        {result.department}
                    </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                    <motion.div
                        animate={result.triage_priority === 'Critical' ? { 
                            scale: [1, 1.1, 1],
                            boxShadow: ['0 0 0 0 rgba(239, 68, 68, 0.4)', '0 0 0 20px rgba(239, 68, 68, 0)', '0 0 0 0 rgba(239, 68, 68, 0)'] 
                        } : {}}
                        transition={result.triage_priority === 'Critical' ? { repeat: Infinity, duration: 2, ease: "easeInOut" } : {}}
                        style={{
                            background: result.triage_priority === 'Critical' ? 'rgba(239, 68, 68, 0.1)' : result.triage_priority === 'High' ? 'rgba(245, 158, 11, 0.1)' : 'rgba(16, 185, 129, 0.1)',
                            color: result.triage_priority === 'Critical' ? 'var(--danger)' : result.triage_priority === 'High' ? '#f59e0b' : '#10b981',
                            padding: '0.75rem 1.5rem', borderRadius: '24px', fontWeight: 900, fontSize: '0.9rem', display: 'inline-flex', alignItems: 'center', gap: '0.75rem', border: `1px solid ${result.triage_priority === 'Critical' ? 'var(--danger)' : result.triage_priority === 'High' ? '#f59e0b' : '#10b981'}`,
                            textTransform: 'uppercase', letterSpacing: '1px'
                        }}
                    >
                        <Award size={20} /> {result.triage_priority} Priority
                    </motion.div>
                </div>
            </div>

            {/* AI Summary and Confidence */}
            <div style={{ marginBottom: '3rem', position: 'relative', zIndex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' }}>
                    <h4 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--text-main)', fontSize: '1.25rem', fontWeight: 900, fontFamily: 'Outfit, sans-serif' }}>
                        <Brain size={24} style={{ color: 'var(--primary)' }} /> Neural Synthesis
                    </h4>
                    <span style={{ fontSize: '1rem', fontWeight: 900, color: confidencePercentage > 80 ? '#10b981' : 'var(--text-soft)', letterSpacing: '0.5px' }}>
                        MATCH PROBABILITY: {confidencePercentage}%
                    </span>
                </div>
                {/* Confidence Bar */}
                <div style={{ height: '10px', background: 'var(--bg-color)', borderRadius: '5px', overflow: 'hidden', marginBottom: '1.5rem', border: '1px solid var(--border-subtle)' }}>
                    <motion.div 
                        initial={{ width: 0 }}
                        animate={{ width: `${confidencePercentage}%` }}
                        transition={{ duration: 1.5, ease: "easeOut" }}
                        style={{
                            height: '100%',
                            background: `linear-gradient(90deg, var(--primary) 0%, ${confidencePercentage > 80 ? '#10b981' : 'var(--accent)'} 100%)`,
                            boxShadow: '0 0 15px var(--primary-glow)'
                        }} 
                    />
                </div>
                <div style={{ background: 'white', padding: '1.75rem', borderRadius: '24px', border: '1px solid var(--border-subtle)', boxShadow: '0 10px 30px -10px rgba(0,0,0,0.05)' }}>
                    <p style={{ margin: 0, color: 'var(--text-main)', lineHeight: '1.7', fontSize: '1.1rem', fontWeight: 500 }}>
                        {result.summary || `Initial clinical telemetry suggests a high-probability correlation with ${result.department} requirements. Proceeding with synchronized triage validation.`}
                    </p>
                </div>
            </div>

            <div style={{ display: 'flex', gap: '1.5rem', marginBottom: '3rem', position: 'relative', zIndex: 1 }}>
                <div style={{ flex: 1, background: 'var(--bg-color)', padding: '1.5rem', borderRadius: '24px', border: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '12px', background: 'white', border: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--primary)' }}>
                        <Clock size={20} />
                    </div>
                    <div>
                        <div style={{ fontSize: '0.75rem', color: 'var(--text-soft)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '1px' }}>Process Duration</div>
                        <div style={{ color: 'var(--text-main)', fontWeight: 900, fontSize: '1.1rem' }}>{result.estimated_duration_minutes} Minutes</div>
                    </div>
                </div>
                <div style={{ flex: 1, background: result.severity_score > 7 ? 'rgba(239, 68, 68, 0.05)' : 'var(--bg-color)', padding: '1.5rem', borderRadius: '24px', border: result.severity_score > 7 ? '1px solid rgba(239, 68, 68, 0.2)' : '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <div style={{ width: '40px', height: '40px', borderRadius: '12px', background: 'white', border: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: result.severity_score > 7 ? 'var(--danger)' : 'var(--primary)' }}>
                        <Thermometer size={20} />
                    </div>
                    <div>
                        <div style={{ fontSize: '0.75rem', color: result.severity_score > 7 ? 'var(--danger)' : 'var(--text-soft)', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '1px' }}>Severity Scalar</div>
                        <div style={{ color: result.severity_score > 7 ? 'var(--danger)' : 'var(--text-main)', fontWeight: 900, fontSize: '1.1rem' }}>{result.severity_score || 5} <span style={{ fontSize: '0.8rem', opacity: 0.6 }}>/ 10</span></div>
                    </div>
                </div>
            </div>

            {/* Immediate Actions */}
            {result.immediate_actions && result.immediate_actions.length > 0 && (
                <div style={{ marginBottom: '3.5rem', background: 'linear-gradient(135deg, #f8fafc 0%, white 100%)', padding: '2rem', borderRadius: '24px', border: '1px solid var(--border-subtle)', position: 'relative', zIndex: 1 }}>
                    <h4 style={{ margin: '0 0 1.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--text-main)', fontSize: '1.1rem', fontWeight: 900, textTransform: 'uppercase', letterSpacing: '1px' }}>
                        <CheckCircle2 size={24} style={{ color: '#10b981' }} /> Protocol Reinforcement
                    </h4>
                    <ul style={{ margin: 0, paddingLeft: '0', listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                        {result.immediate_actions.map((action, idx) => (
                            <li key={idx} style={{ display: 'flex', alignItems: 'start', gap: '0.75rem', fontSize: '1rem', color: 'var(--text-soft)', fontWeight: 600 }}>
                                <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#10b981', marginTop: '8px', flexShrink: 0, boxShadow: '0 0 8px #10b981' }} />
                                {action}
                            </li>
                        ))}
                    </ul>
                </div>
            )}

            <motion.button
                whileHover={{ scale: 1.02, boxShadow: '0 20px 40px -10px var(--primary-glow)' }}
                whileTap={{ scale: 0.98 }}
                onClick={onProceed}
                style={{
                    width: '100%', padding: '1.5rem', background: 'var(--primary)', color: 'white',
                    border: 'none', borderRadius: '20px', fontSize: '1.25rem', fontWeight: 900,
                    cursor: 'pointer', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '1rem',
                    boxShadow: '0 10px 25px -5px var(--primary-glow)', textTransform: 'uppercase', letterSpacing: '1px'
                }}>
                <Calendar size={24} /> Initialize Specialist Sync
            </motion.button>
        </motion.div>
    );
};

export default AnalysisResult;
